In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0) # also tf.float32 implicitly
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [3]:
writer = tf.summary.FileWriter('.')
writer.add_graph(tf.get_default_graph())

In [4]:
sess = tf.Session()
print(sess.run(total))

7.0


In [5]:
print(sess.run({'ab':(a, b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [6]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.01866734 0.8774215  0.88216126]
[0.6058942  0.36930668 0.24427187]
(array([1.9090889, 1.7226151, 1.2568994], dtype=float32), array([2.9090889, 2.7226152, 2.2568994], dtype=float32))


In [7]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [8]:
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [13]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [16]:
init = tf.global_variables_initializer()
sess.run(init)

In [17]:
print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[-0.3347479]
 [-1.9280708]]


In [20]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.layers.dense(x, units=1)

init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[-0.5331286]
 [-3.8039033]]


### Regression Training

In [21]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

In [22]:
linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)

In [23]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

print(sess.run(y_pred))

[[-1.3550473]
 [-2.7100947]
 [-4.065142 ]
 [-5.4201894]]


In [24]:
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

print(sess.run(loss))

3.7206764


In [25]:
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

In [26]:
for i in range(100):
    _, loss_value = sess.run((train,loss))
    print(loss_value)

3.7206764
2.6128314
1.843935
1.3102281
0.9397166
0.6824437
0.503746
0.37957057
0.29322833
0.23313877
0.19126663
0.16203597
0.1415782
0.1272087
0.11706479
0.10985399
0.10467943
0.10091875
0.0981402
0.09604413
0.09442262
0.09313139
0.09207034
0.09117001
0.09038214
0.089673296
0.08902028
0.08840694
0.08782208
0.08725797
0.08670918
0.086171925
0.0856437
0.085122585
0.08460738
0.08409715
0.08359131
0.083089456
0.082591206
0.08209642
0.08160487
0.081116475
0.08063115
0.080148846
0.0796695
0.079193026
0.07871946
0.07824878
0.07778089
0.07731581
0.07685356
0.07639403
0.07593728
0.07548324
0.075031966
0.07458333
0.07413742
0.07369417
0.073253565
0.07281558
0.072380245
0.071947485
0.07151732
0.07108973
0.07066468
0.07024222
0.06982223
0.069404796
0.06898981
0.068577364
0.06816734
0.06775977
0.06735466
0.06695192
0.06655165
0.06615375
0.06575821
0.06536506
0.064974256
0.064585775
0.06419963
0.06381579
0.06343424
0.06305499
0.06267799
0.06230326
0.06193074
0.061560474
0.061192416
0.06082655
0.0604

In [27]:
my_image = tf.zeros([10, 299, 299, 3])

In [31]:
r = tf.rank(my_image)
print(r)

Tensor("Rank_3:0", shape=(), dtype=int32)


In [33]:
sess = tf.Session()
constant = tf.constant([1, 2, 3])
tensor = constant * constant
print(tensor.eval())

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`

In [34]:
c = tf.constant([1, 2, 3])
t = c * c
tf.Print(t, [t])  # This does nothing
t = tf.Print(t, [t])  # Here we are using the value returned by tf.Print
result = t + 1  # Now when result is evaluated the value of `t` will be printed.

In [35]:
result.eval()

ValueError: Cannot evaluate tensor using `eval()`: No default session is registered. Use `with sess.as_default()` or pass an explicit session to `eval(session=sess)`